### ISSUE TITLE
grunt forever:restart is not working

### ISSUE THREAD

**Issue by alexserver** [bustardcelly/grunt-forever#20]
I'm working with grunt-contrib-watch and grunt-forever together, so if any file changes, I order forever to restart via : forever:<section>:restart. This is apparently working, but when I refresh the browser updates are not being shown, so I suppose there is a bug within grunt-forever and forever itself.
this is my grunt config:
    forever: {
     server: {
       options: {
         index: 'app.js',
         logDir: 'logs/'
       }        
     }
    },
    watch: {
      web: {
        files: ['examples/*js'],
        tasks: ['browserify', 'forever:server:restart']
      },
    }

**Comment by bustardcelly** [comment]
Should be fixed in v0.4.6 with this commit https://github.com/bustardcelly/grunt-forever/commit/100b7d89eb1b926670d47ec437ea0a5336b8ab72

**Comment by pmaoui** [comment]
This issue is still not resolved in the v0.4.7 for me unfortunately.
