### ISSUE TITLE
ENOENT Error

### ISSUE THREAD

**Issue by rainabba** [bustardcelly/grunt-forever#30]
My grunt task looks like:
```
    forever: {
      server: {
        options: {
          index: 'lib/index.js',
          logDir: 'log'
        }
      }
    }
```

I've also tried using just 'index.js' in the root of my app (same folder as gruntfile.js) to eliminate that. At the console I get "Monitor died unexpectedly with exit code 0". I can run "node lib/index.js" and my app is fine. Below is what I find in log/log.log (err.log and out.log are empty).

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

This is happening with a simple launch of "grunt forever:server" and "grunt forever:server:start".

I miss something?

**Comment by stevenalanstark** [comment]
same issue here, this is my log.log:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn c:\Program ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)

**Comment by stevenalanstark** [comment]
FIXED!

https://github.com/bustardcelly/grunt-forever/issues/29

If you change the version of forever in grunt-forever, everything just works fine. :)

vi node_modules\grunt-forever\package.json

change the version

in cmd, navigate to the node_modile\grunt-forever\ folder

run:

npm install -d

it will now work

**Comment by rainabba** [comment]
Closing and getting ready to submit a pull-request.
