### ISSUE TITLE
output being logged to two different files?

### ISSUE THREAD

**Issue by getify** [bustardcelly/grunt-forever#32]
Here's my `grunt-forever` config:

```
forever: {
        main: {
                options: {
                        index: "index.js",
                        logDir: ".",
                        logFile: "output.txt",
                        errFile: "error.txt"
                }
        }
}
```

The "output.txt" file is being written, but **also** the default "out.log" file is being written. Why both? How do I stop the default file from being created and written to?

**Comment by bustardcelly** [comment]
Hello @getify,

forever has 3 different log files (described in the CLI options https://github.com/foreverjs/forever/blob/master/README.md): OUTFILE, LOGFILE, and ERRFILE.

The "out.log" file you see being generated is the OUTFILE, while the "output.txt" file specified is the LOGFILE.

I believe the additional log file was a recent change to forever, and this PR for grunt-forever added support for the additional file: https://github.com/bustardcelly/grunt-forever/commit/2e03bcf253760fae39e1416921c8fb9ed77a9ec6

if you specify an `outFile` option in your grunt-forever task config, it should dump to whatever specified file and the "out.log" will not be generated.

**Comment by getify** [comment]
> I believe the additional log file was a recent change to forever, and this PR for grunt-forever added support for the additional file: 2e03bcf

I would suggest that this new `outFile` option should be added to this `grunt-forever`'s README. ;-)

**Comment by getify** [comment]
Also, your current documentation says:

> logFile string
> File stdout is logged into, defaults to 'out.log'.

Seems like that is inaccurate compared to your code. `logFile` is "log.log", `outFile` is "out.log".

**Comment by getify** [comment]
And, is there no option for me to tell grunt-forever to **not** set one or more of these options? If I use forever itself, and I don't put one of those options in, I believe its default behavior is to not set them. So it's strange that grunt-forever forces me to specify all 3.

I think most would assume, like me, that omitting one from my grunt-forever config should be the same thing as not having it passed to forever at all.

**Comment by bustardcelly** [comment]
issues added. thank you for the suggestions :)

https://github.com/bustardcelly/grunt-forever/issues/33
https://github.com/bustardcelly/grunt-forever/issues/34

**Comment by getify** [comment]
Thanks! :)
